Feature background image
rsnazario/Proj4_Background_Images pull request #1
Opened 2019-12-16 17:42 UTC by rsnazario

This is the first submit of the project 4 : Background images and gradient.

One question: the stickler keeps asking to change the indentation to 2 spaces instead of tabs. Is that really required?

2019-12-16 18:32 UTC, pelzolga123 commented on index.html
> +                    <li> <a href=""> Support </a> </li>
`href` should not be empty. You can just add '#'.

2019-12-16 18:32 UTC, pelzolga123 commented on index.html
> +                    <a href=""><p class="what"></p></a>
`href` should not be empty. You can just add '#'.

2019-12-16 18:32 UTC, pelzolga123 commented on index.html
> +                <a href=""><p class="adv sust"></p></a>
`href` should not be empty. You can just add '#'.

2019-12-16 18:32 UTC, pelzolga123 commented on index.html
> +                <h6>Shop the <a href="">Apple Online Store</a> (1-800-MY-APPLE), visit an <a href=""> Apple Retail Store,</a> or find a <a href=""> reseller.</a> </h6> <br>
`href` should not be empty. You can just add '#'.

2019-12-16 18:32 UTC, pelzolga123 commented on index.html
> +                <li> <a href=""> <img src="https://web.archive.org/web/20140301004610im_/http://images.apple.com/global/elements/flags/16x16/usa.png" alt="Choose your country or region" height="16" w
`href` should not be empty. You can just add '#'.

2019-12-16 18:34 UTC, pelzolga123 requested changes
Pull request description should have info only about project. Stickler needs to be working correctly. Readme should be more descriptive. Bottom part requires some styling changes.

2019-12-16 18:34 UTC, pelzolga123 commented
## Hi Rafael! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### Your project looks :+1: amazing!

 But there are things to change before this project can be approved:
* [ ] Your `.stickler.yml` file is present but not configured. You need to fix that. As for your question in pull request description: yes, you need to fix everything required, no matter how unimportant it seems. 
* [ ] Pull request description should only have information about changes in this project. For example:
  1. Added header with linear gradient background.
  2. Added bottom section with four images.
And so on. [Link to pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
* [ ] Readme file should be more descriptive. Please take a look at template [here](https://github.com/microverseinc/readme-template) to make it better. 
* [ ] Every `<a>` tag should have some link inside, to another pages or just '#'. 
* [ ] The bottom part styling is a little messed up, please make it look exactly like original. 
![image](https://user-images.githubusercontent.com/20416431/70932324-27730080-2042-11ea-8ec2-b6bbd57eeae6.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/70932472-82a4f300-2042-11ea-8a9f-b7f002972d2c.png)

### Please kindly fix the above issues and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2019-12-16 22:45 UTC, nikasulo requested changes
# Hello @rsnazario, you have made a nice attempt!
There are a few things you need to look into before this project can be approved. Please take a look below:

##### Readme
Your project will benefit from a more descriptive readme file. It will make it look more professional and make your project look more interesting.
![screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_readme.png)

##### Stickler
Stickler is still throwing errors as regards the code you've written, please look into it and make sure there are no errors before requesting another review.

##### Design
You made a nice attempt but please look very closely at the original page and ensure your design matches up closely. Look at the spacing between elements, the spacing in elements, the width of each element and make sure you can't tell much of a difference between the original site and your project.

## Summary
Please look into all that has been outlined above, improve the design, write a more descriptive readme file and correct stickler errors! When all this is done, request another review! Thanks :smile:

2019-12-17 14:46 UTC, rsnazario commented
I am sorry about the README file, I was updating the one on Master Branch by mistake ><

2019-12-17 15:58 UTC, nikasulo requested changes
# Nice job with the readme! @rsnazario 
Please take a look at the stickler errors next and lastly the layout. The current layout doesn't match the original page.

2019-12-17 16:48 UTC, imhta approved these changes
# Project approved 🎉 

### Hello  @rsnazario  , 👋 You have done a great job in this project 👏 

<img src="https://thumbs.gfycat.com/SpeedyAmazingIndianpalmsquirrel-size_restricted.gif">


----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

2019-12-17 17:10 UTC, merged